export const PRODUCTS = [
  "Aster Sculptural Mini Dress",
  "Calyx Draped Midi Dress",
  "Luna Cutout Knit Top",
  "Helios Pleated Maxi Skirt",
  "Solstice Raffia Tote",
  "Petra Beaded Shoulder Bag",
  "Muse Metallic Sandal",
  "Orchid Strapless Top",
  "Ripple Mesh Bodysuit",
  "Arc Resin Bangle",
  "Sable Wide-Leg Trouser",
  "Eden Satin Slip Dress",
  "Nova Halter Mini Dress",
  "Dune Linen Blazer",
  "Fable Cropped Cardigan",
  "Vela Ruched Mini Skirt",
  "Citrine Statement Earring",
  "Halo Heeled Mule",
  "Mirage Sheer Column Dress",
  "Cove Structured Tote",
  "Sylph Corset Top",
  "Iris Sculptural Clutch",
  "Drift Knit Midi Dress",
  "Tide Wrap Top",
  "Aurora Satin Wide Leg",
  "Grove Crochet Mini Dress",
  "Mica Chain Necklace",
  "Wisp Asymmetric Tank",
  "Prism Pleated Pant",
  "Bloom Cutout Maxi Dress",
  "Gala Strap Sandal",
  "Ember Ribbed Dress",
  "Rhea Denim Jacket",
  "Pearl Drop Earring",
  "Crescent Shoulder Bag",
  "Saffron Linen Short",
  "Opal Sheer Blouse",
  "Maris Draped Top",
  "Atlas Utility Pant",
  "Nectar Mini Tote",
  "Breeze Poplin Shirt",
  "Petal Knit Skirt",
  "Violet Cutout Dress",
  "Quartz Hoop Earring",
  "Waverly Maxi Dress",
  "Noir Sculpted Heel",
  "Seabird Raffia Hat",
  "Terra Twill Trench",
  "Siren Bias Midi",
  "Vale Organza Top",
  "Cassis Knit Set",
  "Cinder Wrap Dress",
  "Aloe Satin Skirt",
  "Cameo Corset Dress",
  "Poppy Knit Tank",
  "Citrine Mini Clutch",
  "Fawn Slingback Heel",
  "Ecru Tailored Vest",
  "Zephyr Pleated Dress",
  "Koru Statement Ring",
];

